runtime: python39  # Specify Python 3.9 runtime

instance_class: F2  # Optional: Defines the instance type (F2 is the default for lightweight apps)

env_variables:
  PORT: 8080  # Ensure the correct port for App Engine
